SELECT TRIM(B.CTT_DESC01) AS SETOR_UNIMED,
        TRIM(A.RA_TELEFON) AS TELEFONE/*,
        TRIM(A.RA_EMAIL)   AS EMAIL*/
  FROM SIGA.VW_SRA010 A,
        SIGA.CTT010 B
 WHERE A.RA_MAT = ?
   AND B.CTT_CUSTO = A.RA_CC