SELECT FT.DATAINICIAL AS DATA_INICIAL_TETO_COBRANCA
      ,FT.DATAFINAL   AS DATA_FINAL_TETO_COBRANCA
      ,FT.VALORTETOPF AS VALOR_TETO_COBRANCA
FROM   SAM_FAMILIA_TETO_PF FT 
WHERE  FT.FAMILIA = ?
AND    FT.HANDLE  = (SELECT MAX(FT1.HANDLE) FROM SAM_FAMILIA_TETO_PF FT1 WHERE FT1.FAMILIA = FT.FAMILIA)