SELECT --DISTINCT 
  'P' AS TIPO_RESPONSAVEL,
  CPES.HANDLE AS ID_RESP_FINANCEIRO,
  CPES_ENDC.BAIRRO AS BAIRRO,
  CPES_ENDC.CEP AS CEP,
  CPES_MUNENDC.NOME AS CIDADE,
  CPES.CNPJCPF AS CNPJ_CPF,
  CPES_ENDC.COMPLEMENTO AS COMPLEMENTO,
  CPES.NOME AS CONTRAT_PAGADOR_NOME,
  CPES.DATASAIDA AS DATA_EXCLUSAO,
  CPES.DATAENTRADA AS DATA_INCLUSAO,
  CPES.DATANASCIMENTO AS DATA_NASCIMENTO,
  CPES_ENDC.DDDCELULAR AS DDD_CELULAR,
  CPES_ENDC.DDD1 AS DDD,
  CPES_ENDC.DDD1 AS DDD_COMERCIAL,
  CASE
    WHEN (SELECT 1 FROM SFN_CONTAFIN CPES_CFIN, SFN_CONTAFIN_COMPLEMENTO CPES_CFIC WHERE CPES_CFIN.PESSOA = CPES.HANDLE AND CPES_CFIN.HANDLE = CPES_CFIC.CONTAFINANCEIRA AND CPES_CFIC.DATAINICIAL <= TRUNC(SYSDATE) AND ( CPES_CFIC.DATAFINAL IS NULL OR CPES_CFIC.DATAFINAL >= TRUNC(SYSDATE) ) AND NVL(CPES_CFIC.CONTACORRENTE, '0') <> '0' AND ROWNUM = 1) = 1 THEN 'S' 
    ELSE 'N'
  END AS DEBITO_AUT,
  (SELECT CPES_AGE.AGENCIA FROM SFN_AGENCIA CPES_AGE, SFN_CONTAFIN CPES_CFIN, SFN_CONTAFIN_COMPLEMENTO CPES_CFIC WHERE CPES_CFIN.PESSOA = CPES.HANDLE AND CPES_CFIN.HANDLE = CPES_CFIC.CONTAFINANCEIRA AND CPES_CFIC.DATAINICIAL <= TRUNC(SYSDATE) AND ( CPES_CFIC.DATAFINAL IS NULL OR CPES_CFIC.DATAFINAL >= TRUNC(SYSDATE) ) AND NVL(CPES_CFIC.CONTACORRENTE, '0') <> '0' AND CPES_CFIC.AGENCIA = CPES_AGE.HANDLE AND ROWNUM = 1) AS DEBITO_AUT_AGENCIA,
  (SELECT CPES_BAN.CODIGO FROM SFN_BANCO CPES_BAN, SFN_CONTAFIN CPES_CFIN, SFN_CONTAFIN_COMPLEMENTO CPES_CFIC WHERE CPES_CFIN.PESSOA = CPES.HANDLE AND CPES_CFIN.HANDLE = CPES_CFIC.CONTAFINANCEIRA AND CPES_CFIC.DATAINICIAL <= TRUNC(SYSDATE) AND ( CPES_CFIC.DATAFINAL IS NULL OR CPES_CFIC.DATAFINAL >= TRUNC(SYSDATE) ) AND NVL(CPES_CFIC.CONTACORRENTE, '0') <> '0' AND CPES_CFIC.BANCO = CPES_BAN.HANDLE AND ROWNUM = 1) AS DEBITO_AUT_BANCO,
  (SELECT CPES_CFIC.CONTACORRENTE FROM SFN_CONTAFIN CPES_CFIN, SFN_CONTAFIN_COMPLEMENTO CPES_CFIC WHERE CPES_CFIN.PESSOA = CPES.HANDLE AND CPES_CFIN.HANDLE = CPES_CFIC.CONTAFINANCEIRA AND CPES_CFIC.DATAINICIAL <= TRUNC(SYSDATE) AND ( CPES_CFIC.DATAFINAL IS NULL OR CPES_CFIC.DATAFINAL >= TRUNC(SYSDATE) ) AND NVL(CPES_CFIC.CONTACORRENTE, '0') <> '0' AND ROWNUM = 1) AS DEBITO_AUT_CONTA,
  (SELECT CPES_CFIC.DV FROM SFN_CONTAFIN CPES_CFIN, SFN_CONTAFIN_COMPLEMENTO CPES_CFIC WHERE CPES_CFIN.PESSOA = CPES.HANDLE AND CPES_CFIN.HANDLE = CPES_CFIC.CONTAFINANCEIRA AND CPES_CFIC.DATAINICIAL <= TRUNC(SYSDATE) AND ( CPES_CFIC.DATAFINAL IS NULL OR CPES_CFIC.DATAFINAL >= TRUNC(SYSDATE) ) AND NVL(CPES_CFIC.CONTACORRENTE, '0') <> '0' AND ROWNUM = 1) AS DEBITO_AUT_DIGITO,
  CPES.EMAIL AS EMAIL,
  '('||CPES_ENDC.DDD1||') '||CPES_ENDC.PREFIXO1||'-'||CPES_ENDC.NUMERO1 AS FONE,
  '('||CPES_ENDC.DDDCELULAR||') '||CPES_ENDC.PREFIXOCELULAR||'-'||CPES_ENDC.NUMEROCELULAR AS FONE_CELULAR,
  '('||CPES_ENDC.DDD1||') '||CPES_ENDC.PREFIXO1||'-'||CPES_ENDC.NUMERO1 AS FONE_COMERCIAL,
  CPES_ENDC.LOGRADOURO AS LOGRADOURO,
  CPES_ENDC.NUMERO AS NUMERO,
  CASE
     WHEN (SELECT 1 FROM SFN_CONTAFIN_COMPLEMENTO COM, SFN_CONTAFIN FIN WHERE NVL(COM.CONTACORRENTE, '0') <> '0' AND COM.DATAINICIAL <= TRUNC(SYSDATE) AND ( COM.DATAFINAL IS NULL OR COM.DATAFINAL >= TRUNC(SYSDATE) ) AND COM.CONTAFINANCEIRA = FIN.HANDLE AND FIN.PESSOA = CPES.HANDLE AND ROWNUM = 1) = 1 THEN
       'DEBITO AUTOMATICO'
     WHEN (SELECT 1 FROM SFN_CONTAFIN_TIPODOCUMENTO DOC, SFN_CONTAFIN FIN WHERE DOC.CONTAFINANCEIRA = FIN.HANDLE AND FIN.PESSOA = CPES.HANDLE AND ROWNUM = 1) = 1 THEN
       'BOLETO'
     ELSE
       (SELECT DECODE(FIN.TABGERACAOREC, 1, 'CONTA CORRENTE', 2, 'CARTAO CREDITO', 3, 'BOLETO') FROM SFN_CONTAFIN FIN WHERE FIN.PESSOA = CPES.HANDLE AND ROWNUM = 1)
  END AS TIPO_COBRANCA,
  CASE WHEN CPES.TABFISICAJURIDICA = 1 THEN 'F' WHEN CPES.TABFISICAJURIDICA = 2 THEN 'J' END AS TIPO_PESSOA,
  (SELECT SIGLA FROM ESTADOS WHERE HANDLE = CPES_ENDC.ESTADO) AS UF,
  RAMATI.DESCRICAO AS RAMO_DE_ATIVIDADE,
  TIPDOC.DESCRICAO AS TIPO_DOCUMENTO,
  SYSDATE AS DW_INC,
  SYSDATE AS DW_ALT,
  CFC.DATAINICIAL AS DATA_INICIAL_DEBITO_AUT
,NVL(FAM.HANDLE,0) AS ID_FAMILIA
FROM
  SAM_BENEFICIARIO BEN
  JOIN SAM_FAMILIA FAM ON BEN.FAMILIA = FAM.HANDLE
  JOIN SAM_CONTRATO CON ON FAM.CONTRATO = CON.HANDLE
  JOIN SFN_PESSOA CPES ON CON.PESSOA = CPES.HANDLE
  LEFT OUTER JOIN SAM_ENDERECO CPES_ENDC ON CPES.ENDERECOCORRESPONDENCIA = CPES_ENDC.HANDLE
  LEFT OUTER JOIN MUNICIPIOS CPES_MUNENDC ON CPES_ENDC.MUNICIPIO = CPES_MUNENDC.HANDLE
  LEFT JOIN SAM_RAMOATIVIDADE RAMATI ON CPES.RAMOATIVIDADE = RAMATI.HANDLE
  
  LEFT JOIN SFN_CONTAFIN CONFIN ON CPES.HANDLE = CONFIN.PESSOA
  LEFT JOIN SFN_TIPODOCUMENTO     TIPDOC ON TIPDOC.HANDLE                = CONFIN.TIPODOCUMENTOREC
  LEFT JOIN SFN_CONTAFIN_COMPLEMENTO CFC ON (CFC.CONTAFINANCEIRA = CONFIN.HANDLE AND CFC.DATAFINAL IS NULL AND CFC.FAMILIA = FAM.HANDLE)
WHERE BEN.HANDLE = ?