SELECT -- DISTINCT 
  'P' AS TIPO_RESPONSAVEL,
  LPES.HANDLE AS ID_RESP_FINANCEIRO,
  LPES_ENDC.BAIRRO AS BAIRRO,
  LPES_ENDC.CEP AS CEP,
  LPES_MUNENDC.NOME AS CIDADE,
  LPES.CNPJCPF AS CNPJ_CPF,
  LPES_ENDC.COMPLEMENTO AS COMPLEMENTO,
  LPES.NOME AS CONTRAT_PAGADOR_NOME,
  LPES.DATASAIDA AS DATA_EXCLUSAO,
  LPES.DATAENTRADA AS DATA_INCLUSAO,
  LPES.DATANASCIMENTO AS DATA_NASCIMENTO,
  LPES_ENDC.DDDCELULAR AS DDD_CELULAR,
  LPES_ENDC.DDD1 AS DDD,
  LPES_ENDC.DDD1 AS DDD_COMERCIAL,
  CASE
    WHEN (SELECT 1 FROM SFN_CONTAFIN LPES_CFIN, SFN_CONTAFIN_COMPLEMENTO LPES_CFIC WHERE LPES_CFIN.PESSOA = LPES.HANDLE AND LPES_CFIN.HANDLE = LPES_CFIC.CONTAFINANCEIRA AND LPES_CFIC.DATAINICIAL <= TRUNC(SYSDATE) AND ( LPES_CFIC.DATAFINAL IS NULL OR LPES_CFIC.DATAFINAL >= TRUNC(SYSDATE) ) AND NVL(LPES_CFIC.CONTACORRENTE, '0') <> '0' AND ROWNUM = 1) = 1 THEN 'S' 
    ELSE 'N'
  END AS DEBITO_AUT,
  (SELECT LPES_AGE.AGENCIA FROM SFN_AGENCIA LPES_AGE, SFN_CONTAFIN LPES_CFIN, SFN_CONTAFIN_COMPLEMENTO LPES_CFIC WHERE LPES_CFIN.PESSOA = LPES.HANDLE AND LPES_CFIN.HANDLE = LPES_CFIC.CONTAFINANCEIRA AND LPES_CFIC.DATAINICIAL <= TRUNC(SYSDATE) AND ( LPES_CFIC.DATAFINAL IS NULL OR LPES_CFIC.DATAFINAL >= TRUNC(SYSDATE) ) AND NVL(LPES_CFIC.CONTACORRENTE, '0') <> '0' AND LPES_CFIC.AGENCIA = LPES_AGE.HANDLE AND ROWNUM = 1) AS DEBITO_AUT_AGENCIA,
  (SELECT LPES_BAN.CODIGO FROM SFN_BANCO LPES_BAN, SFN_CONTAFIN LPES_CFIN, SFN_CONTAFIN_COMPLEMENTO LPES_CFIC WHERE LPES_CFIN.PESSOA = LPES.HANDLE AND LPES_CFIN.HANDLE = LPES_CFIC.CONTAFINANCEIRA AND LPES_CFIC.DATAINICIAL <= TRUNC(SYSDATE) AND ( LPES_CFIC.DATAFINAL IS NULL OR LPES_CFIC.DATAFINAL >= TRUNC(SYSDATE) ) AND NVL(LPES_CFIC.CONTACORRENTE, '0') <> '0' AND LPES_CFIC.BANCO = LPES_BAN.HANDLE AND ROWNUM = 1) AS DEBITO_AUT_BANCO,
  (SELECT LPES_CFIC.CONTACORRENTE FROM SFN_CONTAFIN LPES_CFIN, SFN_CONTAFIN_COMPLEMENTO LPES_CFIC WHERE LPES_CFIN.PESSOA = LPES.HANDLE AND LPES_CFIN.HANDLE = LPES_CFIC.CONTAFINANCEIRA AND LPES_CFIC.DATAINICIAL <= TRUNC(SYSDATE) AND ( LPES_CFIC.DATAFINAL IS NULL OR LPES_CFIC.DATAFINAL >= TRUNC(SYSDATE) ) AND NVL(LPES_CFIC.CONTACORRENTE, '0') <> '0' AND ROWNUM = 1) AS DEBITO_AUT_CONTA,
  (SELECT LPES_CFIC.DV FROM SFN_CONTAFIN LPES_CFIN, SFN_CONTAFIN_COMPLEMENTO LPES_CFIC WHERE LPES_CFIN.PESSOA = LPES.HANDLE AND LPES_CFIN.HANDLE = LPES_CFIC.CONTAFINANCEIRA AND LPES_CFIC.DATAINICIAL <= TRUNC(SYSDATE) AND ( LPES_CFIC.DATAFINAL IS NULL OR LPES_CFIC.DATAFINAL >= TRUNC(SYSDATE) ) AND NVL(LPES_CFIC.CONTACORRENTE, '0') <> '0' AND ROWNUM = 1) AS DEBITO_AUT_DIGITO,
  LPES.EMAIL AS EMAIL,
  '('||LPES_ENDC.DDD1||') '||LPES_ENDC.PREFIXO1||'-'||LPES_ENDC.NUMERO1 AS FONE,
  '('||LPES_ENDC.DDDCELULAR||') '||LPES_ENDC.PREFIXOCELULAR||'-'||LPES_ENDC.NUMEROCELULAR AS FONE_CELULAR,
  '('||LPES_ENDC.DDD1||') '||LPES_ENDC.PREFIXO1||'-'||LPES_ENDC.NUMERO1 AS FONE_COMERCIAL,
  LPES_ENDC.LOGRADOURO AS LOGRADOURO,
  LPES_ENDC.NUMERO AS NUMERO,
  CASE
     WHEN (SELECT 1 FROM SFN_CONTAFIN_COMPLEMENTO COM, SFN_CONTAFIN FIN WHERE NVL(COM.CONTACORRENTE, '0') <> '0' AND COM.DATAINICIAL <= TRUNC(SYSDATE) AND ( COM.DATAFINAL IS NULL OR COM.DATAFINAL >= TRUNC(SYSDATE) ) AND COM.CONTAFINANCEIRA = FIN.HANDLE AND FIN.PESSOA = LPES.HANDLE AND ROWNUM = 1) = 1 THEN
       'DEBITO AUTOMATICO'
     WHEN (SELECT 1 FROM SFN_CONTAFIN_TIPODOCUMENTO DOC, SFN_CONTAFIN FIN WHERE DOC.CONTAFINANCEIRA = FIN.HANDLE AND FIN.PESSOA = LPES.HANDLE AND ROWNUM = 1) = 1 THEN
       'BOLETO'
     ELSE
       (SELECT DECODE(FIN.TABGERACAOREC, 1, 'CONTA CORRENTE', 2, 'CARTAO CREDITO', 3, 'BOLETO') FROM SFN_CONTAFIN FIN WHERE FIN.PESSOA = LPES.HANDLE AND ROWNUM = 1)
  END AS TIPO_COBRANCA,
  CASE WHEN LPES.TABFISICAJURIDICA = 1 THEN 'F' WHEN LPES.TABFISICAJURIDICA = 2 THEN 'J' END AS TIPO_PESSOA,
  (SELECT SIGLA FROM ESTADOS WHERE HANDLE = LPES_ENDC.ESTADO) AS UF,
  RAMATI.DESCRICAO AS RAMO_DE_ATIVIDADE,
  TIPDOC.DESCRICAO AS TIPO_DOCUMENTO,
  SYSDATE AS DW_INC,
  SYSDATE AS DW_ALT,
  CFC.DATAINICIAL AS DATA_INICIAL_DEBITO_AUT
,NVL(FAM.HANDLE,0) AS ID_FAMILIA
FROM
  SAM_BENEFICIARIO BEN
  JOIN SAM_FAMILIA FAM ON BEN.FAMILIA = FAM.HANDLE
  JOIN SAM_CONTRATO CON ON FAM.CONTRATO = CON.HANDLE
  JOIN SAM_CONTRATO_LOTACAO CLOT ON FAM.LOTACAO = CLOT.HANDLE
  JOIN SFN_PESSOA LPES ON CLOT.PESSOAFATURAMENTO = LPES.HANDLE
  LEFT OUTER JOIN SAM_ENDERECO LPES_ENDC ON LPES.ENDERECOCORRESPONDENCIA = LPES_ENDC.HANDLE
  LEFT OUTER JOIN MUNICIPIOS LPES_MUNENDC ON LPES_ENDC.MUNICIPIO = LPES_MUNENDC.HANDLE
  LEFT JOIN SAM_RAMOATIVIDADE RAMATI ON LPES.RAMOATIVIDADE = RAMATI.HANDLE
  
  LEFT JOIN SFN_CONTAFIN CONFIN ON LPES.HANDLE = CONFIN.PESSOA
  LEFT JOIN SFN_TIPODOCUMENTO     TIPDOC ON TIPDOC.HANDLE                = CONFIN.TIPODOCUMENTOREC
  LEFT JOIN SFN_CONTAFIN_COMPLEMENTO CFC ON (CFC.CONTAFINANCEIRA = CONFIN.HANDLE AND CFC.DATAFINAL IS NULL AND CFC.FAMILIA = FAM.HANDLE)
WHERE
  BEN.HANDLE = ?